[package]
name = "r_station"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
prost = "0.11"
sled = "0.34"
serde = { version = "1.0", features = ["derive"] }
itertools = "0.11"
chrono = "0.4"

[build-dependencies]
prost-build = "0.11"
